jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      
      #- sfdx/auth:
      #    defaultusername: akhiltandon1984@brave-narwhal-ongk8f.com
      #    consumerKey: HUB_CONSUMER_KEY
      #    jwtKey: CERT_KEY
      #    decryption_key: DECRYPTION_KEY

      - run:
          name: Create hub key
          command: |
            #echo 'make hub key'
            echo $CERT_KEY | base64 -di > assets/server1.key 
            #openssl enc -nosalt -aes-256-cbc -d -in $CERT_KEY -out assets/server1.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
            #openssl enc -aes-256-cbc -d -in $CERT_KEY -out assets/server1.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
            sfdx force:auth:jwt:grant --clientid $HUB_CONSUMER_KEY --jwtkeyfile assets/server1.key --username $HUB_SFDX_USER -a deploy -s
      
      - run:
          command: >
            echo You now have access to the sfdx cli and may execute commands
            against it.

            sfdx auth:list
          name: Run your SFDX commands here
orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
version: 2.1
workflows:
  basic-test:
    jobs:
      - install_authenticate
