jobs:
  install_authenticate:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      
      #- sfdx/auth:
      #    defaultusername: akhiltandon1984@brave-narwhal-ongk8f.com
      #    consumerKey: HUB_CONSUMER_KEY
      #    jwtKey: CERT_KEY
      #    decryption_key: DECRYPTION_KEY

      - run:
          name: Create hub key
          command: |
            echo 'make hub key'
            echo $CERT_KEY | base64 -di > server1.key
            #- mkdir keys
            #- echo $HUB_SERVER_KEY_HEX | xxd -r -ps >> keys/hub.key
             openssl enc -nosalt -aes-256-cbc -d -in $CERT_KEY -out assets/server1.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
            #- openssl rsa -in keys/hub.key -check -noout
          ### Uncomment the following if performing deployments
          #- echo 'make deploy key'
          #- echo $DEPLOY_SERVER_KEY_HEX | xxd -r -ps >> keys/deploy.key
          #- openssl rsa -in keys/deploy.key -check -noout
           sfdx force:auth:jwt:grant --clientid $HUB_CONSUMER_KEY --jwtkeyfile assets/server1.key --username $HUB_SFDX_USER -a deploy
      
      - run:
          command: >
            echo You now have access to the sfdx cli and may execute commands
            against it.

            sfdx auth:list
          name: Run your SFDX commands here
orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0
version: 2.1
workflows:
  basic-test:
    jobs:
      - install_authenticate
